apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: "sample"
  annotations:
    backstage.io/techdocs-ref:
      dir: .
spec:
  type: service
  owner: user:ymaki
  lifecycle: experimental
